### ISSUE TITLE
The submitButton is disabled..

### ISSUE THREAD

**Issue by jzhang6** [formvalidation/formvalidation#1160]
@nghuuphuoc 

I have a question regarding submit button in the following scenario.

I have a form containing some visible fields and some invisible fields, when the form is initially  loaded, I click the submit button, it will disable the button as some visible fields with invalid data, then I correct the data in these visible fields and the submit button is enabled after that, and then I ENABLE the INVISIBLE fields and enter the data ...Whatever I input in these fields, the submit button is always disabled..

Please advise how to fix this.

Thanks.

**Comment by nghuuphuoc** [comment]
@adamrunner 
It's fixed in the [latest code](https://github.com/formvalidation/formvalidation/archive/master.zip).
You can download the latest code and try again.

__IMPORTANT__: You might have to look at [the upgrading guide](http://formvalidation.io/news/upgrading-to-v0.6.0/) if using the latest code.

**Comment by adamrunner** [comment]
@nghuuphuoc thanks for tracking down the issue and solving! great support, love the plugin. I ended up working around my issue, but I'll look at implementing the update during my next code push on this project.

**Comment by cdomkokao** [comment]
How did you work around the issue?  I would love to know because I can't get mine to work.
