### ISSUE TITLE
Integrating with Bootstrap material design

### ISSUE THREAD

**Issue by faebuk** [formvalidation/formvalidation#1205]
Hey there

I'm currently using your bootstrapvalidator with the "bootstrap-material-design". I created now a form with some text and radiobuttons. 

If I enter something the text gets validated, but the radiobuttons don't. 

JSFiddle:
http://jsfiddle.net/ckL3zqaz/2/

if you need the whole code, just say it.

- Issue at "bootstrap-material-design" https://github.com/FezVrasta/bootstrap-material-design/issues/240

Greetings 
faebuk

**Comment by nghuuphuoc** [comment]
When using with other plugins, you must follow [these principles](http://formvalidation.io/examples/#compatibility).

In your case, the radios are not visible because it is set ```display: none``` by bootstrap-material-design.
You need to ask the plugin not ignore them by setting 

```javascript
$('#registerForm').bootstrapValidator({
    excluded: [':disabled']
});
```

See the working jsfiddle: http://jsfiddle.net/ckL3zqaz/4/

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_

**Comment by nghuuphuoc** [comment]
Here is the example for v0.6.0: http://formvalidation.io/examples/bootstrap-material-design/
