### ISSUE TITLE
Credit Card Validation Returns wrong type

### ISSUE THREAD

**Issue by michaelguild13** [formvalidation/formvalidation#1308]
When entering this credit card number: 5555555555554444 ( Master Card )
The returned type is Diner Club Card but those numbers are for a Master Card

For an example go to the demo:
bootstrapvalidator/demo/selector.html

**Comment by nghuuphuoc** [comment]
@michaelguild13 
Thank for reporting. The reason is that both Diners Club __for US__ and Master Card have 16 digits and accept 54, 55 prefixes.
According to some sources, such as [this](http://www.stevemorse.org/ssn/List_of_Bank_Identification_Numbers.html):

> Diners Club: Card numbers begin with 36 or 38. (There are Diners Club cards that begin with 5. These are a joint venture between Diners Club and MasterCard, and are processed like a MasterCard.)

So, in this case, I think ```DINERS_CLUB_US``` and ```MASTERCARD``` types are the same.
I also updated the [Showing card icon](http://formvalidation.io/validators/creditCard/#showing-card-icon) example.

**Comment by michaelguild13** [comment]
Ah! Good to know. Thanks @nghuuphuoc.
