### ISSUE TITLE
Overriding default options $.extend Not Work!!

### ISSUE THREAD

**Issue by slion0725** [formvalidation/formvalidation#1331]
http://formvalidation.io/examples/overriding-default-options/
    $.fn.formValidation.DEFAULT_OPTIONS = $.extend({}, $.fn.formValidation.DEFAULT_OPTIONS, {
        message: 'The field is not valid',
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        }
    });

No icon show!!

and

how can i use " framework: 'bootstrap', " add in " $.fn.formValidation.DEFAULT_OPTIONS " ???

**Comment by nghuuphuoc** [comment]
Oh, I missed this example. This example isn't listed in the [examples](http://formvalidation.io/examples/) page because it's not supported anymore.

Behide the sences, because the plugin supports many frameworks, each have default options. So, it's not possible to do that (at least for me, I tried it so much while developing new v0.6.0 version).
