### ISSUE TITLE
Name conflict

### ISSUE THREAD

**Issue by periscuelo** [formvalidation/formvalidation#1376]
Good Afternoon.
In First Place, sorry about my english and congratulations for your work.

"Name conflict
Do not use the properties of a form, such as submit, reset, length, method to set the name or id attribute of form, field elements. Name conflicts can cause the problem.
For example, you cannot submit the form after validating if use submit to name the Submit button:"

I read this, and i have this problem with version 0.5.2. And i can't beleave when i put a div tag before the form and the problem desappear. Just have a class and works: < div class="col-md-12" > before of form and everything is all right.

This is not a bug?

http://jsfiddle.net/periscuelo/7o85vvbt/ not working example
http://jsfiddle.net/periscuelo/efkcs2up/ working example

**Comment by nghuuphuoc** [comment]
The plugin automatically [enables](http://formvalidation.io/examples/html5/) the validators for fields using HTML 5 inputs.
In your form, ```<input type="email" name="email" placeholder="Email Alternativo" />``` will be validated using the [emailAddress validator](http://formvalidation.io/validators/emailAddress/) since it uses HTML 5 ```type="email"```.

And if we don't wrap this email field inside ```.form-group``` or ```col-xx-yy``` (xx can be ```sm```, ```md```, ..., yy can be 1 to 12), there will be a problem as you mentioned.

In this case, you can [disable](http://formvalidation.io/examples/attribute/) the validators on field by 
1) setting ```type="text"``` ---> http://jsfiddle.net/7o85vvbt/4/
2) or add ```data-fv-emailaddress="false"``` ---> http://jsfiddle.net/7o85vvbt/3/

PS: There is nothing wrong with your English. It's very good :)

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_

**Comment by periscuelo** [comment]
Thanks for the alternative as the validation and for the generosity with my English :P

I really need to keep the type and name as email in the code I'm working on.But I still have a question that remains. Why <input type= "email" name="email" placeholder="Email Alternativo" /> worked with the div class="col-md-12" and without date-fv-emailaddress = "false" ?

Thank you for your help

**Comment by nghuuphuoc** [comment]
When working with Bootstrap form, the field and its label must follow the Bootstrap form structure.
The field and its label must be placed inside a ```.form-group``` or ```.col-xx-yy``` element.
If not, you will see the [error message](http://formvalidation.io/getting-started/#writing-form) in Console window (look at the red color message at the right)

![error](https://cloud.githubusercontent.com/assets/4226036/5876366/3791c67a-a349-11e4-8fed-b0693b68b9b8.png)

(Of course, the plugin allows to organize [complex form](http://formvalidation.io/getting-started/#complex-form)).

That's why it works when you place the email field inside ```div class="col-md-12"```.

Here is working [fiddle](http://jsfiddle.net/periscuelo/7o85vvbt/) when I do this:

```html
<form id="orcamento" role="form">
    <div class="col-md-12">
        <input type="email" name="email" placeholder="Email Alternativo" />
    </div>
    ...
</form>
```

**Comment by periscuelo** [comment]
These guys who want to program everything anyway with no default is fire. Then comes even talk that is bug kkkkk. Thank you for the clarification.
In truth i not used that input within the bootstrap structure because initially it was type hidden. If is hidden not has cause being inside a formgroup or div.
But I understand why and I also saw that you have alternatives for these cases.
Thanks again.

**Comment by nghuuphuoc** [comment]
I hope these information help you understand more about how the plugin works.
Can you close the issue?

**Comment by periscuelo** [comment]
Of course, helped me a lot, thank you
