### ISSUE TITLE
Tags lost

### ISSUE THREAD

**Issue by prolic** [formvalidation/formvalidation#1440]
All tags are lost, we nailed towards 0.5.3 and now history seems overwritten?!

**Comment by olekhy** [comment]
we not needed this crappy stuff best ever validation ;) imho

**Comment by nghuuphuoc** [comment]
The reason I removed the tags because I got many supported/questions from new bible (who try to download/use tags from Releases page) related to the old versions which are named as BootstrapValidator.
I was trying to move the latest 0.5.x to other [repos](https://github.com/nghuuphuoc/bootstrapvalidator) which supports Bower.
You can try again.

**Comment by olekhy** [comment]
@nghuuphuoc fine thx.

**Comment by nghuuphuoc** [comment]
Moving/re-organizing the old Bootstrapvalidator and FormValidation repos help me support the user of separated versions better.
I'm sorry if there is any inconvenience.

**Comment by paquitodev** [comment]
@nghuuphuoc well I was using Bower and after run a `bower update` my complete development goes down due to tags removal, why? when it will be available again trough Bower? Do I need to install it over and over downloading the library?
